events:
  logwatch_aws_mail:
    enabled: true
    type: AwsSesEmailHook
    sender: "{{ sender_address }}"
    sender_name: "{{ sender_name }}"
    region: "{{ aws_region }}"
    recipients:
      - "{{ recipient_address}}"
